[k8s_masters]
Morpheus-RHEL ansible_host=44.206.240.84 ansible_user=root

[k8s_workers]
K8s_Worker_1 ansible_host=34.236.156.219 ansible_user=root
K8_Worker_2 ansible_host=107.22.6.240 ansible_user=root

[k8s_all:children]
k8s_masters
k8s_workers
